In [ ]:
# ------------------------------- 2. DATA UNDERSTANDING  ------------------------------------

In [10]:
import pandas as pd

customers = pd.read_csv(r"C:\Users\kinis\Downloads\ecommerce-fraud-analytics\data_1\raw_data\olist_customers_dataset.csv")

orders = pd.read_csv(r"C:\Users\kinis\Downloads\ecommerce-fraud-analytics\data_1\raw_data\olist_orders_dataset.csv")

payments = pd.read_csv(r"C:\Users\kinis\Downloads\ecommerce-fraud-analytics\data_1\raw_data\olist_order_payments_dataset.csv")

reviews = pd.read_csv(r"C:\Users\kinis\Downloads\ecommerce-fraud-analytics\data_1\raw_data\olist_order_reviews_dataset.csv")

In [12]:
# Data Understanding 
# 1. Customer Table & purpose is to retrieve Customer details
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [13]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB

In [14]:
customers.describe(include='all')

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
count,99441,99441,99441.000000,99441,99441
unique,99441,96096,NaN,4119,27
top,06b8999e2fba1a1fbc88172c00ba8bc7,8d50f5eadf50201ccdcedfb9e2ac8455,NaN,sao paulo,SP
freq,1,17,NaN,15540,41746
mean,NaN,NaN,35137.474583,NaN,NaN
std,NaN,NaN,29797.938996,NaN,NaN
min,NaN,NaN,1003.000000,NaN,NaN
25%,NaN,NaN,11347.000000,NaN,NaN
50%,NaN,NaN,24416.000000,NaN,NaN
75%,NaN,NaN,58900.000000,NaN,NaN
max,NaN,NaN,99990.000000,NaN,NaN

In [15]:
# 2. Order table & purpose is to retrieve Order Transactions
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [16]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

In [17]:
orders.describe(include='all')

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
count,99441,99441,99441,99441,99281,97658,96476,99441
unique,99441,99441,8,98875,90733,81018,95664,459
top,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2018-03-31 15:08:21,2018-02-27 04:31:10,2018-05-09 15:48:00,2018-05-14 20:02:44,2017-12-20 00:00:00
freq,1,1,96478,3,9,47,3,522

In [18]:
# 3. Payments table & purpose is to retrieve Payment information
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [19]:
payments.info()

<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB

In [20]:
payments.describe(include='all')

,order_id,payment_sequential,payment_type,payment_installments,payment_value
count,103886,103886.000000,103886,103886.000000,103886.000000
unique,99440,NaN,5,NaN,NaN
top,fa65dad1b0e818e3ccc5cb0e39231352,NaN,credit_card,NaN,NaN
freq,29,NaN,76795,NaN,NaN
mean,NaN,1.092679,NaN,2.853349,154.100380
std,NaN,0.706584,NaN,2.687051,217.494064
min,NaN,1.000000,NaN,0.000000,0.000000
25%,NaN,1.000000,NaN,1.000000,56.790000
50%,NaN,1.000000,NaN,1.000000,100.000000
75%,NaN,1.000000,NaN,4.000000,171.837500
max,NaN,29.000000,NaN,24.000000,13664.080000

In [21]:
#4. Review table & purpose is to retrieve customer feedback
reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [22]:
reviews.info()

<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  str
 4   review_comment_message   40977 non-null  str
 5   review_creation_date     99224 non-null  str
 6   review_answer_timestamp  99224 non-null  str
dtypes: int64(1), str(6)
memory usage: 5.3 MB

In [23]:
reviews.describe(include='all')

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
count,99224,99224,99224.000000,11568,40977,99224,99224
unique,98410,98673,NaN,4527,36159,636,98248
top,c444278834184f72b1484dfe47de7f97,c88b1d1b157a9999ce368f218a407141,NaN,Recomendo,Muito bom,2017-12-19 00:00:00,2017-06-15 23:21:05
freq,3,3,NaN,423,230,463,4
mean,NaN,NaN,4.086421,NaN,NaN,NaN,NaN
std,NaN,NaN,1.347579,NaN,NaN,NaN,NaN
min,NaN,NaN,1.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,4.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,5.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,5.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,5.000000,NaN,NaN,NaN,NaN

In [24]:
# FIND KEYS 
# Customers 
customers.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='str')

In [25]:
# Orders
orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='str')

In [26]:
# Payments
payments.columns

Index(['order_id', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='str')

In [27]:
# Reviews
reviews.columns

Index(['review_id', 'order_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp'],
      dtype='str')

In [ ]:
# ------------------------------- 2. DATA CLEANING  ------------------------------------

In [28]:
import numpy as np
#2.1 --- Check missing values

customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [29]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [30]:
orders[orders.isnull().any(axis=1)]   #inspect the missing values

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaN,NaN,2017-05-09 00:00:00
44,ee64d42b8cf066f35eac1cf57de1aa85,caded193e8e47b8362864762a83db3c5,shipped,2018-06-04 16:44:48,2018-06-05 04:31:18,2018-06-05 14:32:00,NaN,2018-06-28 00:00:00
103,0760a852e4e9d89eb77bf631eaaf1c84,d2a79636084590b7465af8ab374a8cf5,invoiced,2018-08-03 17:44:42,2018-08-07 06:15:14,NaN,NaN,2018-08-21 00:00:00
128,15bed8e2fec7fdbadb186b57c46c92f2,f3f0e613e0bdb9c7cee75504f0f90679,processing,2017-09-03 14:22:03,2017-09-03 14:30:09,NaN,NaN,2017-10-03 00:00:00
154,6942b8da583c2f9957e990d028607019,52006a9383bf149a4fb24226b173106f,shipped,2018-01-10 11:33:07,2018-01-11 02:32:30,2018-01-11 19:39:23,NaN,2018-02-07 00:00:00
...,...,...,...,...,...,...,...,...
99283,3a3cddda5a7c27851bd96c3313412840,0b0d6095c5555fe083844281f6b093bb,canceled,2018-08-31 16:13:44,NaN,NaN,NaN,2018-10-01 00:00:00
99313,e9e64a17afa9653aacf2616d94c005b8,b4cd0522e632e481f8eaf766a2646e86,processing,2018-01-05 23:07:24,2018-01-09 07:18:05,NaN,NaN,2018-02-06 00:00:00
99347,a89abace0dcc01eeb267a9660b5ac126,2f0524a7b1b3845a1a57fcf3910c4333,canceled,2018-09-06 18:45:47,NaN,NaN,NaN,2018-09-27 00:00:00
99348,a69ba794cc7deb415c3e15a0a3877e69,726f0894b5becdf952ea537d5266e543,unavailable,2017-08-23 16:28:04,2017-08-28 15:44:47,NaN,NaN,2017-09-15 00:00:00
99415,5fabc81b6322c8443648e1b21a6fef21,32c9df889d41b0ee8309a5efb6855dcb,unavailable,2017-10-10 10:50:03,2017-10-14 18:35:57,NaN,NaN,2017-10-23 00:00:00

In [31]:
# check their order status
orders.loc[
    orders["order_delivered_customer_date"].isnull(),
    "order_status"
].value_counts()

order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         8
created           5
approved          2
Name: count, dtype: int64

In [32]:
orders[
    (orders["order_status"] == "delivered") &
    (orders["order_delivered_customer_date"].isnull())
]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
3002,2d1e2d5bf4dc7227b3bfebb81328c15f,ec05a6d8558c6455f0cbbd8a420ad34f,delivered,2017-11-28 17:44:07,2017-11-28 17:56:40,2017-11-30 18:12:23,NaN,2017-12-18 00:00:00
20618,f5dd62b788049ad9fc0526e3ad11a097,5e89028e024b381dc84a13a3570decb4,delivered,2018-06-20 06:58:43,2018-06-20 07:19:05,2018-06-25 08:05:00,NaN,2018-07-16 00:00:00
43834,2ebdfc4f15f23b91474edf87475f108e,29f0540231702fda0cfdee0a310f11aa,delivered,2018-07-01 17:05:11,2018-07-01 17:15:12,2018-07-03 13:57:00,NaN,2018-07-30 00:00:00
79263,e69f75a717d64fc5ecdfae42b2e8e086,cfda40ca8dd0a5d486a9635b611b398a,delivered,2018-07-01 22:05:55,2018-07-01 22:15:14,2018-07-03 13:57:00,NaN,2018-07-30 00:00:00
82868,0d3268bad9b086af767785e3f0fc0133,4f1d63d35fb7c8999853b2699f5c7649,delivered,2018-07-01 21:14:02,2018-07-01 21:29:54,2018-07-03 09:28:00,NaN,2018-07-24 00:00:00
92643,2d858f451373b04fb5c984a1cc2defaf,e08caf668d499a6d643dafd7c5cc498a,delivered,2017-05-25 23:22:43,2017-05-25 23:30:16,NaN,NaN,2017-06-23 00:00:00
97647,ab7c89dc1bf4a1ead9d6ec1ec8968a84,dd1b84a7286eb4524d52af4256c0ba24,delivered,2018-06-08 12:09:39,2018-06-08 12:36:39,2018-06-12 14:10:00,NaN,2018-06-26 00:00:00
98038,20edc82cf5400ce95e1afacc25798b31,28c37425f1127d887d7337f284080a0f,delivered,2018-06-27 16:09:12,2018-06-27 16:29:30,2018-07-03 19:26:00,NaN,2018-07-19 00:00:00

In [33]:
orders.loc[
    orders["order_approved_at"].isnull(),
    "order_status"
].value_counts()

order_status
canceled     141
delivered     14
created        5
Name: count, dtype: int64

In [34]:
#Look at the statuses that appear: If most are canceled, created, or unavailable
#Then the missing approval date is expected.Action: Keep the nulls and document the reason.

#If many are delivered or shipped - That's unusual because an order generally needs approval before
# moving forward. Then inspect those rows:
orders[
    (orders["order_status"].isin(["delivered"])) &
    (orders["order_approved_at"].isnull())
]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
5323,e04abd8149ef81b95221e88f6ed9ab6a,2127dc6603ac33544953ef05ec155771,delivered,2017-02-18 14:40:00,NaN,2017-02-23 12:04:47,2017-03-01 13:25:33,2017-03-17 00:00:00
16567,8a9adc69528e1001fc68dd0aaebbb54a,4c1ccc74e00993733742a3c786dc3c1f,delivered,2017-02-18 12:45:31,NaN,2017-02-23 09:01:52,2017-03-02 10:05:06,2017-03-21 00:00:00
19031,7013bcfc1c97fe719a7b5e05e61c12db,2941af76d38100e0f8740a374f1a5dc3,delivered,2017-02-18 13:29:47,NaN,2017-02-22 16:25:25,2017-03-01 08:07:38,2017-03-17 00:00:00
22663,5cf925b116421afa85ee25e99b4c34fb,29c35fc91fc13fb5073c8f30505d860d,delivered,2017-02-18 16:48:35,NaN,2017-02-22 11:23:10,2017-03-09 07:28:47,2017-03-31 00:00:00
23156,12a95a3c06dbaec84bcfb0e2da5d228a,1e101e0daffaddce8159d25a8e53f2b2,delivered,2017-02-17 13:05:55,NaN,2017-02-22 11:23:11,2017-03-02 11:09:19,2017-03-20 00:00:00
26800,c1d4211b3dae76144deccd6c74144a88,684cb238dc5b5d6366244e0e0776b450,delivered,2017-01-19 12:48:08,NaN,2017-01-25 14:56:50,2017-01-30 18:16:01,2017-03-01 00:00:00
38290,d69e5d356402adc8cf17e08b5033acfb,68d081753ad4fe22fc4d410a9eb1ca01,delivered,2017-02-19 01:28:47,NaN,2017-02-23 03:11:48,2017-03-02 03:41:58,2017-03-27 00:00:00
39334,d77031d6a3c8a52f019764e68f211c69,0bf35cac6cc7327065da879e2d90fae8,delivered,2017-02-18 11:04:19,NaN,2017-02-23 07:23:36,2017-03-02 16:15:23,2017-03-22 00:00:00
48401,7002a78c79c519ac54022d4f8a65e6e8,d5de688c321096d15508faae67a27051,delivered,2017-01-19 22:26:59,NaN,2017-01-27 11:08:05,2017-02-06 14:22:19,2017-03-16 00:00:00
61743,2eecb0d85f281280f79fa00f9cec1a95,a3d3c38e58b9d2dfb9207cab690b6310,delivered,2017-02-17 17:21:55,NaN,2017-02-22 11:42:51,2017-03-03 12:16:03,2017-03-20 00:00:00
63052,51eb2eebd5d76a24625b31c33dd41449,07a2a7e0f63fd8cb757ed77d4245623c,delivered,2017-02-18 15:52:27,NaN,2017-02-23 03:09:14,2017-03-07 13:57:47,2017-03-29 00:00:00
67697,88083e8f64d95b932164187484d90212,f67cd1a215aae2a1074638bbd35a223a,delivered,2017-02-18 22:49:19,NaN,2017-02-22 11:31:06,2017-03-02 12:06:06,2017-03-21 00:00:00
72407,3c0b8706b065f9919d0505d3b3343881,d85919cb3c0529589c6fa617f5f43281,delivered,2017-02-17 15:53:27,NaN,2017-02-22 11:31:30,2017-03-03 11:47:47,2017-03-23 00:00:00
84999,2babbb4b15e6d2dfe95e2de765c97bce,74bebaf46603f9340e3b50c6b086f992,delivered,2017-02-18 17:15:03,NaN,2017-02-22 11:23:11,2017-03-03 18:43:43,2017-03-31 00:00:00

In [35]:
# Remove 14 anomalous records od delivered
orders = orders[
    ~(
        (orders["order_status"] == "delivered") &
        (orders["order_approved_at"].isnull())
    )
]

In [36]:
#now check again if its removed or not
orders.loc[
    orders["order_approved_at"].isnull(),
    "order_status"
].value_counts()

# Missing Approval Dates
#Orders with status "canceled" and "created" were allowed to retain null approval timestamps because approval may 
#never have occurred. 14 delivered orders contained missing approval timestamps, which is inconsistent with the 
#expected business process. These records were removed as data-quality anomalies.

order_status
canceled    141
created       5
Name: count, dtype: int64

In [39]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 146
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [40]:
#2.2 --- Check dupliacate
orders.duplicated().sum()
customers.duplicated().sum()
payments.duplicated().sum()
reviews.duplicated().sum()
#O/P- 0 duplicate

np.int64(0)

In [41]:
#2.3 --- Check Primary key validation
orders["order_id"].nunique() == len(orders)

customers["customer_id"].nunique() == len(customers)

True

In [42]:
#2.4 --- Convert Date columns (Datetime Conversion)
orders.dtypes

order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object

In [43]:
# Convert 
date_cols = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_cols:
    orders[col] = pd.to_datetime(orders[col])

In [44]:
# Now verify if they're convert or not
orders.dtypes

order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

In [45]:
#After converting dates, create these columns:
# 2.5 Feature engineering
#2.5 --- Create Analysis Feature
orders["purchase_year"] = (
    orders["order_purchase_timestamp"].dt.year
)

orders["purchase_month"] = (
    orders["order_purchase_timestamp"].dt.month
)

orders["purchase_day"] = (
    orders["order_purchase_timestamp"].dt.day
)

In [46]:
# Now check
orders[
    ["order_purchase_timestamp",
     "purchase_year",
     "purchase_month",
     "purchase_day"]
].head()

  order_purchase_timestamp  purchase_year  purchase_month  purchase_day
0      2017-10-02 10:56:33           2017              10             2
1      2018-07-24 20:41:37           2018               7            24
2      2018-08-08 08:38:49           2018               8             8
3      2017-11-18 19:28:06           2017              11            18
4      2018-02-13 21:18:39           2018               2            13

In [47]:
# 2.6 --- Create Delivery Metrics (v.imp)- These become KPIs later.
# Delivery Time
orders["delivery_days"] = (
    orders["order_delivered_customer_date"]
    -
    orders["order_purchase_timestamp"]
).dt.days

In [48]:
# Delivery Delay
orders["delivery_delay_days"] = (
    orders["order_delivered_customer_date"]
    -
    orders["order_estimated_delivery_date"]
).dt.days

In [49]:
# Delayed Order Flag
orders["is_delayed"] = np.where(
    orders["delivery_delay_days"] > 0,
    1,
    0
)

In [50]:
# Now check- 
orders["is_delayed"].value_counts()
#o/p- ex- [-4 = Delivered 4 days early],[0 = On time],[3 = Delivered 3 days later]

is_delayed
0    92892
1     6535
Name: count, dtype: int64

In [51]:
# 2.7 Quick Validation
orders[
    [
        "delivery_days",
        "delivery_delay_days"
    ]
].describe()

       delivery_days  delivery_delay_days
count   96462.000000         96462.000000
mean       12.093996           -11.875391
std         9.552390            10.183586
min         0.000000          -147.000000
25%         6.000000           -17.000000
50%        10.000000           -12.000000
75%        15.000000            -7.000000
max       209.000000           188.000000

In [ ]:
#What the no.s mean  - delivery_days
#o/p- avg- -12 days, median- 10 days, max- 209 days

#delivery_delay_days
#Mean- -11.88, median- -12, max- 188 now interpretation:Negative values mean:
#Actual Delivery Date   <   Estimated Delivery Date

#In simple words, Most orders were delivered earlier than promised. Ex- 
#Estimated: 20 Jan
#Delivered: 10 Jan
#Delay = -10
#That's why your average delay is negative.
#This is actually a good business insight.

In [52]:
orders.sort_values(
    "delivery_days",
    ascending=False
)[
    [
        "order_id",
        "order_status",
        "delivery_days",
        "delivery_delay_days"
    ]
].head(10)

,order_id,order_status,delivery_days,delivery_delay_days
19590,ca07593549f1816d26a572e06dc1eab6,delivered,209.0,181.0
55619,1b3190b2dfa9d789e1f14c05b647a14a,delivered,208.0,188.0
61610,440d0d17af552815d15a9e41abe49359,delivered,195.0,165.0
70307,2fb597c2f772eca01b1f5c561bf6cc7b,delivered,194.0,155.0
38509,0f4519c5f1c541ddec9f21b3bddd533a,delivered,194.0,161.0
89130,285ab9426d6982034523a855f55a885e,delivered,194.0,166.0
11399,47b40429ed8cce3aee9199792275433f,delivered,191.0,175.0
81401,2fe324febf907e3ea3f2aa9650869fa5,delivered,189.0,167.0
54480,2d7561026d542c8dbd8f0daeadf67a43,delivered,188.0,159.0
68769,c27815f7e3dd0b926b58552628481575,delivered,187.0,162.0

In [53]:
orders.sort_values(
    "delivery_delay_days",
    ascending=False
)[
    [
        "order_id",
        "order_status",
        "delivery_days",
        "delivery_delay_days"
    ]
].head(10)

,order_id,order_status,delivery_days,delivery_delay_days
55619,1b3190b2dfa9d789e1f14c05b647a14a,delivered,208.0,188.0
19590,ca07593549f1816d26a572e06dc1eab6,delivered,209.0,181.0
11399,47b40429ed8cce3aee9199792275433f,delivered,191.0,175.0
81401,2fe324febf907e3ea3f2aa9650869fa5,delivered,189.0,167.0
89130,285ab9426d6982034523a855f55a885e,delivered,194.0,166.0
61610,440d0d17af552815d15a9e41abe49359,delivered,195.0,165.0
68769,c27815f7e3dd0b926b58552628481575,delivered,187.0,162.0
40847,d24e8541128cea179a11a65176e0a96f,delivered,175.0,161.0
38509,0f4519c5f1c541ddec9f21b3bddd533a,delivered,194.0,161.0
54480,2d7561026d542c8dbd8f0daeadf67a43,delivered,188.0,159.0

In [55]:
#Creating cleaned files
customers.to_csv(
    r"C:\Users\kinis\Downloads\ecommerce-fraud-analytics\data_1\cleaned_data\customers_clean.csv",
    index=False
)

orders.to_csv(
    r"C:\Users\kinis\Downloads\ecommerce-fraud-analytics\data_1\cleaned_data\orders_clean.csv",
    index=False
)

payments.to_csv(
    r"C:\Users\kinis\Downloads\ecommerce-fraud-analytics\data_1\cleaned_data\payments_clean.csv",
    index=False
)

reviews.to_csv(
    r"C:\Users\kinis\Downloads\ecommerce-fraud-analytics\data_1\cleaned_data\reviews_clean.csv",
    index=False
)

In [56]:
pip install psycopg2-binary sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psycopg2-binary in C:\Users\kinis\AppData\Roaming\Python\Python314\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in C:\Users\kinis\AppData\Roaming\Python\Python314\site-packages (2.0.50)
Requirement already satisfied: greenlet>=1 in C:\Users\kinis\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\kinis\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [57]:
#Connect python to postgresql 
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql://postgres:shrey123@localhost:5432/ecommerce"
)

In [58]:
# Load Cleaned CSV
#Creating cleaned files
import pandas as pd
customers = pd.read_csv(r"C:\Users\kinis\Downloads\ecommerce-fraud-analytics\data_1\cleaned_data\customers_clean.csv")

orders = pd.read_csv(r"C:\Users\kinis\Downloads\ecommerce-fraud-analytics\data_1\cleaned_data\orders_clean.csv")

payments = pd.read_csv(r"C:\Users\kinis\Downloads\ecommerce-fraud-analytics\data_1\cleaned_data\payments_clean.csv")

reviews = pd.read_csv(r"C:\Users\kinis\Downloads\ecommerce-fraud-analytics\data_1\cleaned_data\reviews_clean.csv")

In [59]:
# Send to postgresql 
# Customers
customers.to_sql(
    "customers",
    engine,
    if_exists="replace",
    index=False
)

441

In [60]:
# Orders
orders.to_sql(
    "orders",
    engine,
    if_exists="replace",
    index=False
)

427

In [61]:
# Payments
payments.to_sql(
    "payments",
    engine,
    if_exists="replace",
    index=False
)

886

In [63]:
# Review
reviews.to_sql(
    "reviews",
    engine,
    if_exists="replace",
    index=False
)

224